### ISSUE TITLE
Jobs issues

### ISSUE THREAD

**Issue by jvenegas96** [ElMedievo-UdeC/Network#16]
Segun dice usuario Fliko32: "no se si lo han dicho pero al momento de elegir algún trabajo hay algunos que al tratar de ver su descripción el cuadro de texto sale fuera de la pantalla y no logras saber de que va la cosa"

**Comment by BGMP** [comment]
@teszeo if you could look into this, that'd be fantastic

**Comment by teszeo** [comment]
@jvenegas96 ESC » OPTIONS » VIDEO SETTINGS » GUI Scale = AUTO.

If that doesnt work tell me.

**Comment by BGMP** [comment]
Closed due to no further updates. Feel free to comment any and I'll re-open.
