### ISSUE TITLE
Tip de alerta por migración

### ISSUE THREAD

**Issue by Lynsosa** [ElMedievo-UdeC/Network#20]
Colocar como tip dentro de los ya existentes uno sobre la migración del host, para recordarle a los usuarios dejar su enderchest e inventario en cofres normales.

**Comment by BGMP** [comment]
~~Gracias por sugerirlo! Lo pondré cuando tengamos un tiempo estimado fijo para el siguiente cambio de host.~~ @teszeo lo resolverá lol

**Comment by teszeo** [comment]
Se agregara en el siguiente restart.
