### ISSUE TITLE
Re-introduce rain

### ISSUE THREAD

**Issue by BGMP** [ElMedievo-UdeC/Network#24]
Thoughts? @teszeo @Lynsosa ?

Not sure if this module is actually working or not, might as well just try and disable it from there? But in general, should we allow rain at all?

https://github.com/ElMedievo-UdeC/Network/blob/6d4bb3c59d15bba9ca06eb33b2b580fe359824b8/Commons/src/main/java/cl/bgmp/commons/modules/WeatherModule.java#L7-L28

**Comment by Prodigy4532** [comment]
Just keep the ability to enable or disable it, i can turn it on rn bc users want it.

**Comment by BGMP** [comment]
Fixed by https://github.com/ElMedievo-UdeC/Network/commit/5867634be7487d1cbb8abc4061229f26a3e6ed1d .
