### ISSUE TITLE
Cannot use /hub command with Commons-Bungee

### ISSUE THREAD

**Issue by teszeo** [ElMedievo-UdeC/Network#25]
![image](https://user-images.githubusercontent.com/55764934/83879825-e233af80-a703-11ea-93c6-6763652137d4.png)

![image](https://user-images.githubusercontent.com/55764934/83879802-d9db7480-a703-11ea-9971-b5896a1898d3.png)

**Comment by BGMP** [comment]
Fixed in https://github.com/ElMedievo-UdeC/Network/commit/58a160430c5392d7b2eaa0e6747b417ab598b25f .
