### ISSUE TITLE
Issue with /msg with Commons-Bungee

### ISSUE THREAD

**Issue by teszeo** [ElMedievo-UdeC/Network#29]
You can see the past msg u sent with /r

![image](https://user-images.githubusercontent.com/55764934/83882147-4d32b580-a707-11ea-9426-0a6d7a708f4b.png)

**Comment by BGMP** [comment]
Now this is odd. Will have to look into nick's formatting as well.

**Comment by BGMP** [comment]
Fixed in https://github.com/ElMedievo-UdeC/Network/commit/d1dfb7f8c95bbc0cf11dc684a6daa465eff23d25 .
