### ISSUE TITLE
Error when you switch servers.

### ISSUE THREAD

**Issue by teszeo** [ElMedievo-UdeC/Network#30]
Only error on console, you can connect to servers and do /hub but this error is always someone change server.

![image](https://user-images.githubusercontent.com/55764934/83937028-cf19f180-a78e-11ea-87fa-b47158ab2319.png)

**Comment by BGMP** [comment]
Fixed itself. Probably dependencies wouldn't fetch correctly when testing, or server had an outdated HexaCord version.
